name: Pysen Check - Experiments
on:
  pull_request:
    paths:
      - experiments/**
  push:
    branches:
      - main
    paths:
      - experiments/**

jobs:
  pysen-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.5"

      - name: Install dependencies
        run: |
          cd experiments
          uv pip install -r requirements.txt --system

      - name: Run Pysen
        run: uv run pysen run lint
